name: great-british-beer
services:
- name: web
  source_dir: /
  github:
    repo: yourusername/great-british-beer
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm greatbritishbeer.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    value: "your_secret_key_here"
  - key: ALLOWED_HOSTS
    value: "*.ondigitalocean.app"
databases:
- name: db
  engine: PG
  num_nodes: 1
  size: basic-xs
