# Generated by Django 4.2.7 on 2026-01-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
