# Generated by Django 4.2.7 on 2026-01-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_brewery_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Sponsored/promoted beer'),
        ),
    ]
